### ISSUE TITLE
[Design] As a PM, I would like to have the final design

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/shorten-link-mac#11]
## Why

- As a discussion with @nmint8m, the current design lacks some features. As a Project manager, I need to see the final design to catch up requirements and prepare backlogs for the team.

## Acceptance Criteria

- Sign-in screen
- Sign-out and Quit
- Input alias and password form
- Edit link form

## Design

https://www.figma.com/file/tlKEISYnh9fZ8b27NiAvH1/macOS-menu-bar-app-team-library?node-id=318%3A53

**Comment by nmint8m** [comment]
The design has been made on (Figma)[https://www.figma.com/file/tlKEISYnh9fZ8b27NiAvH1/macOS-menu-bar-app-team-library?node-id=318%3A53].

<img width="1440" alt="Screen Shot 2021-11-01 at 15 57 18" src="https://user-images.githubusercontent.com/23162627/139647126-132c8d73-7c2a-441b-b25c-30b8459dea93.png">

I also built 2 flows on Figma, please press the `Play` button to check them out.

**Comment by nmint8m** [comment]
@vnntsu Please help me to verify if the UI is fulfilled enough for development.
