### ISSUE TITLE
[UI] As a user, I can delete a shortened link

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/shorten-link-mac#15]
## Why

- User can delete any link after creating, but there is a popup show up to ask user to confirm the delete action
 
## Acceptance Criteria

- Show a confirmation popup:
  - message: `Are you sure to delete this Nimble Link “shortened link”?`
  - additional message: `This action cannot be undone.`
  - 2 buttons: `cancel` and `delete`

![Screen Shot 2021-11-08 at 10 50 48](https://user-images.githubusercontent.com/17830319/140681630-acc20d34-fdf1-4884-a52c-91c64f88620e.png)

## Design

https://www.figma.com/file/tlKEISYnh9fZ8b27NiAvH1/macOS-menu-bar-app-team-library?node-id=418%3A1372

**Comment by blyscuit** [comment]
This design is an alert for older macOS, on Big Sur and forward, the alert is a square type 

![image](https://user-images.githubusercontent.com/6356137/142856840-c02d3bc9-09e3-4a2e-a8a6-da85a6f8fe05.png)

On older device the alert will appear just as the design. Is this OK?

**Comment by vnntsu** [comment]
@blyscuit  Okay noted dude, thanks 🙏
