### ISSUE TITLE
[Integrate] As a user, I can use shortcut key to create a shortened link

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/shorten-link-mac#18]
## Why

- With the shortcut: `⇧+⌘+L` to quickly make a shortened link. This action automatically copies the shortened link that has just been made to the clipboard as well.
 
## Acceptance Criteria

Check the `clipboard` memory.
1. In case it's empty -> Do nothing
2. In case there is a text, check if the text is
    -  not a link -> Do nothing
    - a link:
       - call API to create shortened link
       - Open the app's overlay to inform the user that the link has been created.

**Comment by blyscuit** [comment]
@vnntsu Which screen is the `Open the app's overlay` 🤔 Just open the pop over screen right?

**Comment by vnntsu** [comment]
oh I first think we should show a message after creating a link on the bottom of the overlay view. What do you think?

**Comment by blyscuit** [comment]
Cool, I'll try to see if there's an easy way to show auto close popup. Or else I suggest using Notification.
