### ISSUE TITLE
[Integrate] As a user, I can see list of shortened link

### ISSUE THREAD

**Issue by vnntsu** [nimblehq/shorten-link-mac#8]
## Why

- After users make shortened links successfully, the list of links will be shown right below the text field. 
- Users also can copy and delete the link
 
## Acceptance Criteria

- After calling API, show a list of links

**Comment by vnntsu** [comment]
@blyscuit  I saw the PR linked to this issue has been merged. But this issue is in development still. Are you working on it? or I will close it

**Comment by blyscuit** [comment]
Please close this 🙏
